### ISSUE TITLE
[test request] verify recovery from failed windowed PoST

### ISSUE THREAD

**Issue by raulk** [filecoin-project/oni#12]
**What would you like us to test?**

Verify that miners can recover from faults in window PoST.

**Technical implementation details.**

Except from call (@yusefnapora's notes):

```
- lukasz:
    - in fil, you prove each sector once per day, which we currently do in 36 windows per day (every 40 mins)
    - each sector is assigned to a proving window, miner computes window PoST and submits it
    - if proof is missing, sector is marked faulty - miner gets 2 week window to recover the sector
      - recovery process:
        - before the window is open, you can declare that you will recover the faulty sector, then you have to submit the proof in the correct window.
    - raul q: where does slashing come into this process?
       - lukasz: when your sector is reported faulty, the power for that sector is removed
       - also, when your sector is marked faulty, you pay a fee (b/c the storage is missing)
    - actors are responsible for proving that you didn't prove a sector & tracking what was lost/recovered
    - lotus needs to look at what sectors it needs to prove in the next window
      - also needs to detect faults on disk
    - proving works using a windowed PoST scheduler
      - looks at what blocks come in from the network
        - for every block, asks the miner actor if there's a new proving window open
          - if so, it waits a few blocks (for confidience threshold), computes a window PoST
        - if there's a chain-reorg, the client needs to detect whether their proof was included in the final chain and resubmit if not
    - before running windowed PoST, we scan sectors to make sure we can read from disk
      - it's still possible that a fault can occur even if the sector is readable during the scan (could be intermittent failure, or the fault exists in a part of the sector that wasn't scanned)
    - this will likely be hard to test due to the long time frames (fault recovery period lasts 2 weeks)
      - even mock tests can take minutes
      - magik: we have some tests that claim block time is 25seconds, but actually produce block in a few milliseconds. Still takes a while, but much faster than with stock params
      - why: time is actually measured in blocks, not wall-clock time
        - in tests, we can say "mine the next block" at arbitrary times, can sync/wait on everyone receiving that block
      - wyatt: while you can fake the block time to an extent, running the proofs takes real time, so it's not possible to completely elimitate time. e.g. if you're testing recovery, computing the power table reqires real proofs / time
      - magik: mining a block with 2k sectors takes 30 seconds
      - raul: are proofs necessary for all tests, or can they be faked?
        - magik: not necessary for many tests. we already have fairly powerful & accurate mocks for proofs
          - they behave in much the same way, but aren't safe / secure.
          - using the DI system, you can easily swap out any component with a few lines of code
            - uber/fx with a custom layer on top
```

**What should we measure?**

- Behaviour under chain reorgs, after posting proof.
- Behaviour under chain reorgs, prior to posting proof.
- Behaviour under network partitions.
- Failed sector reads during proof generation (transitorily corrupt the sector?).
- Slashing effective after 2 week period (how can we accelerate the grace period?)

**Which components are involved?**

TBD.

**On a scale from 0-10, what's the proposed _**discomfort factor**_? In other words, how uncomfortable would you be if we went live **without** having tested this? Explain why.**

TBD.

**Additional remarks.**

Failed window PoST nuked previous testnets.

Requestor: @travisperson.
More technical details: @magik6k, @whyrusleeping.
